### PR TITLE
add OnHandshake

### PR DESCRIPTION
**Pull request by zeropool**
User can hijack the RPC connection through OnHandshake

### CODE REVIEW

**Comment by valyala** [comment]
Why you cannot use [Server.Listener](https://godoc.org/github.com/valyala/gorpc#Server) or [Server.OnConnect](https://godoc.org/github.com/valyala/gorpc#Server) for custom connection hijacking? See how [NewTLSServer](https://godoc.org/github.com/valyala/gorpc#NewTLSServer) [is implemented](https://github.com/valyala/gorpc/blob/master/transport.go#L219) - it wraps bare TCP connection into TLS connection.

**Comment by zeropool** [comment]
because I want one port can serve RPC , also can serve my custom service, by handshake byte, I can decide which service client want request. for some condition, firewall only allow one custom port for external connections.

发自我的 iPhone

**Comment by zeropool** [comment]
```go
server.OnHandshake = func(handshakeByte byte, remoteAddr string, rwc io.ReadWriteCloser) bool {
    if handshakeByte == 2 {
        log.Println(remoteAddr, "Connect for Broadcast")
        HandleBroadcast(rwc)
        return true
	} 
    log.Println(remoteAddr, "Connect for GoRPC")
    return false
}
```

**Comment by valyala** [comment]
Just create custom [Listener](https://godoc.org/github.com/valyala/gorpc#Listener). Something like the following (I didn't test it, but you should get the idea):

```go
type customListener struct {
    ln net.Listener
}

func (ln *customListener) Accept() (conn io.ReadWriteCloser, clientAddr string, err error) {
    for {
        c, err := ln.ln.Accept()
        if err != nil {
            return nil, "", fmt.Errorf("cannot accept new connection: %s", err)
        }

        // read handshake byte
        var buf [1]byte
        if _, err = c.Read(buf[:]); err != nil {
            return nil, "", fmt.Errorf("cannot read handshake byte: %s", err)
        }
        if buf[0] != 2 {
            log.Printf("Connect for GoRPC: %s\n", c.RemoteAddr())
            return c, c.RemoteAddr().String(), nil
        }

        log.Printf("Connect for Broadcast: %s\n", c.RemoteAddr())
        go HandleBroadcast(c)
    }
}

func (ln *customListener) Close() error {
    return ln.ln.Close()
}

func (ln *customListener) Init(addr string) error {
    var err error
    ln.ln, err = net.Listen("tcp", addr)
    return err
}
```

**Comment by valyala** [comment]
Forgot to mention that in this case you must use custom [DialFunc](https://godoc.org/github.com/valyala/gorpc#DialFunc) for gorpc Client, which sends the first non-2 byte after dialing to the server:

```go
customDialFunc = func(addr string) (conn io.ReadWriteCloser, err error) {
    c, err := net.Dial("tcp", addr)
    if err != nil {
        return nil, err
    }

    // send non-2 byte to conn in order to distinguish from Broadcast connections
    buf := []byte{0}
    if _, err = c.Write(buf); err != nil {
        c.Close()
        return nil, err
    }
    return c, nil
}
```

**Comment by zeropool** [comment]
serverHandleConnection in serverHandler read the handshake bytes again when Accept return.

https://github.com/valyala/gorpc/blob/master/server.go#L221

 ```go
go serverHandleConnection(s, conn, clientAddr, workersCh)
```

https://github.com/valyala/gorpc/blob/master/server.go#L242

```go
	zChan := make(chan bool, 1)
	go func() {
		var buf [1]byte
		if _, err = conn.Read(buf[:]); err != nil {
			if stopping.Load() == nil {
				s.LogError("gorpc.Server: [%s]->[%s]. Error when reading handshake from client: [%s]", clientAddr, s.Addr, err)
			}
		}
		zChan <- (buf[0] != 0)
	}()
```

this will broke the RPC handshake.

**Comment by valyala** [comment]
> serverHandleConnection in serverHandler read the handshake bytes again when Accept return.
See the updated answer above. Or you can wrap the original connection into something the following:

```go
type firstByteConn struct {
    net.Conn
    firstByte byte
    firstByteRead bool
}

func (c *firstByteConn) Read(p []byte) (int, error) {
    if !c.firstByteRead {
        c.firstByteRead = true
        p[0] = c.firstByte
        return 1, nil
    }
    return c.Conn.Read(p)
}
```

**Comment by zeropool** [comment]
this method is not gracefully, but also thanks, my client is like:

```
    conn, err := net.Dial("tcp", broadcastAddr)
    if err != nil {
        continue
    }
    // handshake to RPC server, no need change much code in rpc client or rpc server, only patch OnHandshake
    conn.Write([]byte{0x02})
```

I will use OnHandshake patch in my own branch, thanks for this awesome project !

**Comment by valyala** [comment]
Glad to help you, @zeropool. And thanks for the pull request. Unfortunately it cannot be merged, since OnHandshake functionality may be implemented with custom Listener as outlined above.

**Pull request closed without merging**
